title: Conservation Hackers
description: "Helping programmers and conservation scientists work together to save biodiversity"
show_downloads: false
google_analytics:
remote_theme: "mmistakes/minimal-mistakes@4.20.2"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-include-cache
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
search: true
